### ISSUE TITLE
Issue with linkages to .h files

### ISSUE THREAD

**Issue by eryk4pdh** [avandalen/SAM15x15#2]
Fresh install of Arduino.

Installed boards through "board manager"

Selected blink example, board->"SAM15x15" build fails:

```
/Library/Arduino15/packages/SAM15x15/hardware/samd/25.12.17/cores/arduino/Arduino.h:48:17: fatal error: sam.h: No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
exit status 1
Error compiling for board SAM 15x15.
```

**Comment by avandalen** [comment]
Arduino Zero package installation

It is possible to install just the Arduino Zero package, the SAM 15x15 then works as the Arduino Zero, but the extra pins of the SAM 15x15 will not be available.

Select Tools > Boards "..." > Boards Manager...
Select "Arduino SAMD Boards (32-bits ARM Cortex-M0+)"
Select version 1.6.8 with the small "Select version" box, see the image below.
Than click on Install

**Comment by eryk4pdh** [comment]
@avandalen Sorry that is not a resolution to an issue, its a mere workaround that defeats the point of the SAM15x15. Best regards
